# Generated by Django 2.1.7 on 2019-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190223_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
