# Generated by Django 2.1.7 on 2019-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190223_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
